### ISSUE TITLE
Error when referencing a package

### ISSUE THREAD

**Issue by guoxiao0521** [Codefend/rollup-plugin-codefend#21]
Thanks to the author for such a great plugin 
I see the following error when quoting

can you give me some help ?

```cmd
[!] Error: Cannot find module 'D:\xxx\node_modules\rollup-plugin-codefend\lib\esm\options\builder' imported from D:\xxx\node_modules\rollup-plugin-codefend\lib\esm\index.mjs
```
rollup@4.13.0
nodejs 18.15.0

**Comment by Z-n-o-M** [comment]
Hi @guoxiao0521, 

the fix has been released in `v2.0.3`
Thank you for the feedback.
